# Allow documents to be indexed
writable: True

# Content is required for extractor pipeline
embeddings:
  content: True

extractor:
  path: google/flan-t5-base

workflow:
  search:
    tasks:
      - task: extractor
        template: |
          Answer the following question using the provided context.

          Question:
          {text}

          Context:
        action: extractor
