# Add
POST https://ca-txtai-api.greensand-19f121e4.eastus.azurecontainerapps.io/add
Content-Type: application/json

[
  { "id": 1, "text": "US tops 5 million confirmed virus cases" },
  { "id": 2, "text": "Canada's last fully intact ice shelf has suddenly collapsed, forming a Manhattan-sized iceberg" },
  { "id": 3, "text": "Beijing mobilises invasion craft along coast as Taiwan tensions escalate" }
]

# Index
GET https://ca-txtai-api.greensand-19f121e4.eastus.azurecontainerapps.io/index

# Search
GET https://ca-txtai-api.greensand-19f121e4.eastus.azurecontainerapps.io/search?query=virus%20cases

# Delete
POST https://ca-txtai-api.greensand-19f121e4.eastus.azurecontainerapps.io/delete
Content-Type: application/json

[1,2,3]
